const money = n => new Intl.NumberFormat('es-CO',{style:'currency',currency:'COP',maximumFractionDigits:0}).format(n).replace('COP','$');
const $ = (s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const cartKey='sva_cart_v1';
function getCart(){try{return JSON.parse(localStorage.getItem(cartKey)||'[]')}catch{return []}}
function saveCart(items){localStorage.setItem(cartKey,JSON.stringify(items)); updateCartCount()}
function addCart(id){const cart=getCart(); if(!cart.includes(id)) cart.push(id); saveCart(cart); toast('Curso agregado al carrito.');}
function removeCart(id){saveCart(getCart().filter(x=>x!==id)); if(location.pathname.endsWith('carrito.html')) renderCart();}
function updateCartCount(){const el=$('.cart-count'); if(el) el.textContent=getCart().length}
function escHTML(s){const d=document.createElement('div');d.textContent=s;return d.innerHTML}
function toast(msg){let el=$('.toast'); if(!el){el=document.createElement('div');el.className='toast';document.body.append(el)} el.textContent=msg;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function cardHTML(c){return `<article class="course-card"><a class="course-image" href="curso.html?id=${c.id}"><img loading="lazy" src="${c.image}" alt="${escHTML(c.name)}"><span class="course-price-badge">${money(c.price)}</span></a><div class="course-body"><div class="category">${escHTML(c.category)}</div><h3><a href="curso.html?id=${c.id}">${escHTML(c.name)}</a></h3><div class="course-meta"><div class="course-price"><small>COP</small>${money(c.price).replace('$','')}</div><div class="course-actions"><a class="btn btn-secondary btn-sm" href="curso.html?id=${c.id}">Ver</a><button class="btn btn-primary btn-sm" onclick="addCart(${c.id})">Agregar</button></div></div></div></article>`}
function setupNav(){const btn=$('.mobile-menu'),nav=$('.nav'); if(btn&&nav) btn.addEventListener('click',()=>nav.classList.toggle('open')); updateCartCount();}
function renderFeatured(){const box=$('#featuredCourses'); if(!box)return; const ids=[7,32,39,74,84,97]; box.innerHTML=ids.map(id=>cardHTML(COURSES[id-1])).join('')}
function renderCategories(){const box=$('#categoryGrid'); if(!box)return; const counts={}; COURSES.forEach(c=>counts[c.category]=(counts[c.category]||0)+1); const icons=['✚','♡','⚕','◉','⌁','♧','✓','⚙']; box.innerHTML=Object.entries(counts).map(([cat,n],i)=>`<a class="cat-card" href="cursos.html?category=${encodeURIComponent(cat)}"><div class="cat-icon">${icons[i%icons.length]}</div><h3>${escHTML(cat)}</h3><p>Explora la oferta disponible en esta categoría.</p><span>${n} cursos →</span></a>`).join('')}
function setupFaq(){$$('.faq-q').forEach(b=>b.addEventListener('click',()=>b.closest('.faq-item').classList.toggle('open')))}

let catPage=1;
function renderCatalog(){const grid=$('#catalogGrid'); if(!grid)return; const q=($('#search')?.value||'').trim().toLowerCase(); const category=$('#categoryFilter')?.value||''; const price=$('#priceFilter')?.value||''; const sort=$('#sortFilter')?.value||''; let list=COURSES.filter(c=>(!q||c.name.toLowerCase().includes(q))&&(!category||c.category===category)&&(!price||c.price===Number(price)));
 if(sort==='low')list.sort((a,b)=>a.price-b.price); if(sort==='high')list.sort((a,b)=>b.price-a.price); if(sort==='az')list.sort((a,b)=>a.name.localeCompare(b.name,'es'));
 const per=12,pages=Math.max(1,Math.ceil(list.length/per)); catPage=Math.min(catPage,pages); const slice=list.slice((catPage-1)*per,catPage*per); grid.innerHTML=slice.map(cardHTML).join('')||`<div class="empty-state" style="grid-column:1/-1"><h3>No encontramos cursos</h3><p>Prueba con otra palabra o cambia los filtros.</p></div>`;
 $('#resultCount').textContent=`${list.length} cursos encontrados`;
 const pbox=$('#pagination'); pbox.innerHTML=Array.from({length:pages},(_,i)=>`<button class="page-btn ${i+1===catPage?'active':''}" data-page="${i+1}">${i+1}</button>`).join(''); $$('.page-btn',pbox).forEach(b=>b.onclick=()=>{catPage=Number(b.dataset.page);renderCatalog();scrollTo({top:260,behavior:'smooth'})});
}
function setupCatalog(){if(!$('#catalogGrid'))return; const cf=$('#categoryFilter'); [...new Set(COURSES.map(c=>c.category))].sort().forEach(c=>cf.insertAdjacentHTML('beforeend',`<option>${c}</option>`)); const params=new URLSearchParams(location.search); if(params.get('category')) cf.value=params.get('category'); ['search','categoryFilter','priceFilter','sortFilter'].forEach(id=>$('#'+id)?.addEventListener(id==='search'?'input':'change',()=>{catPage=1;renderCatalog()})); renderCatalog();}
function renderDetail(){const root=$('#courseDetail');if(!root)return;const id=Number(new URLSearchParams(location.search).get('id'))||1;const c=COURSES.find(x=>x.id===id)||COURSES[0]; document.title=`${c.name} | Saber Vital Academy`;root.innerHTML=`<div class="detail-grid"><div><div class="detail-media"><img src="${c.image}" alt="${escHTML(c.name)}"></div><div class="detail-copy"><div class="category">${escHTML(c.category)}</div><h1 style="font-size:clamp(2rem,4vw,3.35rem);margin:8px 0 18px">${escHTML(c.name)}</h1><h2>Información del curso</h2><div class="placeholder-box">La ficha académica completa —objetivos, duración, temario, instructor y requisitos— está preparada para recibir el contenido oficial de Saber Vital Academy. Esta versión no inventa información que no haya sido suministrada.</div><h2 style="margin-top:26px">Contenido</h2><div class="placeholder-box">Los módulos, lecciones, videos y materiales se conectarán al aula virtual cuando se cargue el contenido académico oficial del curso.</div></div></div><aside class="buy-card"><div class="category">Inscripción</div><div class="price">${money(c.price)}</div><div class="cop">Precio mostrado en el catálogo suministrado</div><button class="btn btn-primary" onclick="addCart(${c.id})">Agregar al carrito</button><a class="btn btn-secondary" href="cursos.html">Seguir explorando</a><ul class="buy-list"><li>Acceso inmediato al contenido del curso</li><li>Interfaz responsive para móvil y computador</li><li>Pago seguro con pasarela certificada</li></ul></aside></div>`;let ld=document.querySelector('#courseLd');if(!ld){ld=document.createElement('script');ld.type='application/ld+json';ld.id='courseLd';document.head.append(ld)}ld.textContent=JSON.stringify({"@context":"https://schema.org","@type":"Course","name":c.name,"provider":{"@type":"Organization","name":"Saber Vital Academy"},"offers":{"@type":"Offer","price":c.price,"priceCurrency":"COP","availability":"https://schema.org/InStock"}})}
function renderCart(){const listEl=$('#cartList');if(!listEl)return; const ids=getCart(),items=ids.map(id=>COURSES.find(c=>c.id===id)).filter(Boolean); if(!items.length){listEl.innerHTML=`<div class="empty-state"><h3>Tu carrito está vacío</h3><p>Explora el catálogo y agrega las capacitaciones que te interesen.</p><a class="btn btn-primary" style="margin-top:18px" href="cursos.html">Ver cursos</a></div>`;$('#cartSummary').innerHTML='';return} listEl.innerHTML=items.map(c=>`<article class="cart-item"><img src="${c.image}" alt="${c.name}"><div><div class="cat">${c.category}</div><h3>${c.name}</h3><div class="course-price" style="margin-top:7px">${money(c.price)}</div></div><div><button class="remove" onclick="removeCart(${c.id})">Eliminar</button></div></article>`).join(''); const total=items.reduce((s,c)=>s+c.price,0); $('#cartSummary').innerHTML=`<div class="summary-card"><h3>Resumen</h3><div class="summary-row"><span>${items.length} curso${items.length>1?'s':''}</span><strong>${money(total)}</strong></div><div class="summary-row total"><span>Total</span><span>${money(total)}</span></div><button class="btn btn-primary" id="checkoutDemo">Continuar al pago</button><p style="font-size:.74rem;margin-top:12px">La pasarela real se conectará en la fase 2. No se solicitarán datos de pago en esta versión.</p></div>`; $('#checkoutDemo').onclick=()=>toast('El sistema de pago se está integrando. Pronto podrás completar tu compra.');}
function setupAuth(){const form=$('.auth-form');if(!form)return; form.addEventListener('submit',e=>{e.preventDefault(); const fields=[...form.querySelectorAll('input[required]')]; if(fields.some(f=>!f.value.trim())) return toast('Completa todos los campos obligatorios.'); const pwd=form.querySelector('input[name=password]'); const conf=form.querySelector('input[name=confirm]'); if(pwd&&pwd.value.length<6)return toast('Usa una contraseña de mínimo 6 caracteres.');if(pwd&&conf&&pwd.value!==conf.value)return toast('Las contraseñas no coinciden.'); toast('Validación correcta. El sistema de autenticación se está integrando.');})}
function acceptCookies(){localStorage.setItem('sva_cookies','1');const b=document.querySelector('.cookie-banner');if(b)b.classList.remove('show')}
function checkCookies(){if(!localStorage.getItem('sva_cookies')){const b=document.querySelector('.cookie-banner');if(b)setTimeout(()=>b.classList.add('show'),1200)}}
document.addEventListener('DOMContentLoaded',()=>{setupNav();renderFeatured();renderCategories();setupFaq();setupCatalog();renderDetail();renderCart();setupAuth();checkCookies();document.querySelectorAll('video').forEach(v=>{v.setAttribute('controlsList','nodownload');v.addEventListener('contextmenu',e=>e.preventDefault())});})
